### ISSUE TITLE
Allow install on older versions of VSCode (version 1.84.1)?

### ISSUE THREAD

**Issue by dragontheory** [jacobcassidy/vscode-css-nesting-syntax-highlighting#3]
Thank you for this! 

I am on a corporate network and unable to upgrade Visual Studio Code to the latest. Is there a tweak to allow installs on older version of VSCode? 

Error for reference . . .

Can't install 'jacobcassidy.css-nesting-syntax-highlighting' extension because it is not compatible with current version of Visual Studio Code (version 1.84.1)

TIA!

**Comment by jacobcassidy** [comment]
@dragontheory I updated the VSCode engine to allow versions from 1.84.0 and above, so it should work for you now. I haven't tested it since I have the latest VSCode installed, so let me know how it goes (make sure you are installing version 0.1.0 of the CSS Nesting extension).

**Comment by dragontheory** [comment]
Thank you very much! I will check it out at corporate tomorrow and let you know.

**Comment by dragontheory** [comment]
It worked! Thank you again!
